apiVersion: "v2"
name: cluster-api-provider-aws
description: "Helm chart for cluster-api-provider-aws."
home: "https://github.com/giantswarm/cluster-api-provider-aws-app"
version: "2.11.0"
appVersion: "2.3.0"
annotations:
  application.giantswarm.io/team: "phoenix"
  config.giantswarm.io/version: 1.x.x
