name: cluster-api-provider-aws
# This refers to a release in the Giant Swarm fork. The fork closely follows upstream releases unless hotfixes are
# needed. Please read https://github.com/giantswarm/cluster-api-provider-aws/blob/main/README.md on how to create a
# release. Please include the short commit SHA in the tag name, such as `v2.0.2-gs-123abcd`. After changing this
# tag, please run `make generate` to update CRDs and other manifests.

# Changes in this tag include upstream v2.10.x with additional:
#   * Giant Swarm fork modifications (https://github.com/giantswarm/cluster-api-provider-aws/pull/653)
#   * Only manage security groups for ENIs tagged by CAPA (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5813)
#   * Add karpenter IAM Roles to the S3 bucket policy so that karpenter nodes can read userdata (https://github.com/giantswarm/cluster-api-provider-aws/pull/618; we're trying to upstream this at https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/5815 by making the policy configurable)
#   * Check control plane version skew before creating new launch template version (https://github.com/giantswarm/cluster-api-provider-aws/pull/624)
#   * Fix cluster upgrade version skew (https://github.com/giantswarm/cluster-api-provider-aws/pull/631)
#   *   + extra commit 'Conditionally proceed if `isMachinePoolAllowedToUpgradeDueToControlPlaneVersionSkew` returns an error'
#   * Ignore release drift while deleting MachinePool and AWSMachinePool (https://github.com/giantswarm/cluster-api-provider-aws/pull/652; prefer single commit on `release-2.11` branch or newer)
tag: v2.11.0-gs-e794d836b

registry:
  domain: gsoci.azurecr.io

image:
  name: giantswarm/cluster-api-aws-controller

ciliumNetworkPolicy:
  enabled: false

crdConvertOnly: true
crdInstall:
  kubectl:
    image: "giantswarm/kubectl"
    tag: "1.24.10"

aws:
  arn: defaultARN

watchfilter: capi

serviceType: managed

provider:
  region: defaultRegion
  capi:
    accessKeyID: defaultID
    secretAccessKey: defaultKey

serviceMonitor:
  enabled: true

verticalPodAutoscaler:
  enabled: true
