---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: capa-serving-cert
  namespace: capa-system
spec:
  dnsNames:
  - capa-webhook-service.{{ .Release.Namespace }}.svc
  - capa-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-giantswarm
  secretName: capa-webhook-service-cert
