---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.kubernetes.io/managed-by: '{{ .Release.Service }}'
  app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  helm.sh/chart: '{{ .Chart.Name }}'
  app.kubernetes.io/name: '{{ .Chart.Name }}'
  app.kubernetes.io/instance: '{{ .Release.Name }}'
  application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}'
fieldSpecs:
  - path: metadata/labels
    create: true
  - path: spec/template/metadata/labels
    create: true
    kind: Deployment
