# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: "ignored" # not important, we are applying this patch to all CRDs
spec:
  conversion:
    strategy: Webhook
    webhook:
      conversionReviewVersions:
      - v1
      - v1beta1
      clientConfig:
        service:
          namespace: '{{ .Release.Namespace }}'
          name: capa-webhook-service
          path: /convert
          port: 443
