---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capa-controller-manager
  namespace: capa-system
  annotations:
    ignore-check.kube-linter.io/unset-cpu-requirements: "We don't want a CPU limit"
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            requests:
              cpu: 10m
              memory: 250Mi
            limits:
              memory: 512Mi
