---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capa-controller-manager
  namespace: capa-system
spec:
  template:
    spec:
      containers:
        - name: manager
          ports:
            - containerPort: {{ .Values.ports.metrics }}
              name: metrics
              protocol: TCP
