apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml
  - ciliumnetworkpolicy_capa-controller-manager.yaml
  - ciliumnetworkpolicy_capa-default-deny.yaml
  - networkpolicy_capa-controller-manager.yaml

images:
  - name: registry.k8s.io/cluster-api-aws/cluster-api-aws-controller
    newName: "{{.Values.registry.domain}}/{{.Values.image.name}}"
    newTag: "{{.Values.tag}}"

transformers:
  - common-labels.yaml
  - webhook-prefix.yaml

patches:
  - path: crd_cainjection.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-aws
  - path: crd_clusterctl_labels.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-aws
  - path: crd_webhook.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-aws

  - path: delete-issuer.yaml
  - path: deployment-args.yaml
  - path: deployment-metrics-port.yaml
  - path: deployment-iam-role.yaml
  - path: deployment-nodeaffinity.yaml
  - path: deployment-requests-limits.yaml
  - path: deployment-seccomp.yaml
  - path: deployment-securitycontext.yaml
  - path: deployment-toleration.yaml
  - path: delete-namespace.yaml
  - path: delete-serviceaccount-annotation.yaml
  - path: metrics-service-named-port.yaml
  - path: webhook-mutating-certificate.yaml
  - path: webhook-mutating-watchfilter.yaml
  - path: webhook-validating-certificate.yaml
  - path: webhook-validating-watchfilter.yaml
  - path: webhook-service-named-port.yaml
  - path: certificate.yaml
  - path: secret.yaml

  - path: deployment-machine-pool-machines-feature-gate.yaml
    target:
      kind: Deployment
      name: capa-controller-manager
      namespace: capa-system
