namespace: '{{ .Release.Namespace }}'

resources:
  - input/infrastructure-components.yaml

images:
  - name: k8s.gcr.io/cluster-api-aws/cluster-api-aws-controller
    newName: "{{.Values.infrastructure.image.domain}}/{{ .Values.infrastructure.image.name}}"
    newTag: "{{.Values.tag}}"
  - name: registry.k8s.io/cluster-api-aws/cluster-api-aws-controller
    newName: "{{.Values.infrastructure.image.domain}}/{{.Values.infrastructure.image.name}}"
    newTag: "{{.Values.tag}}"

transformers:
  - common-labels.yaml
  - monitoring-annotations.yaml
  - webhook-prefix.yaml

patchesStrategicMerge:
  - delete-issuer.yaml
  - deployment-args.yaml
  - deployment-metrics-port.yaml
  - deployment-iam-role.yaml
  - deployment-nodeaffinity.yaml
  - delete-namespace.yaml
  - delete-serviceaccount-annotation.yaml
  - webhook-watchfilter.yaml
  - webhook-certificate.yaml
  - service-add-metrics-port.yaml
  - certificate.yaml
  - secret.yaml

patches:
  - path: crd_cainjection.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-aws
  - path: crd_webhook.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: cluster.x-k8s.io/provider=infrastructure-aws
