apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: cluster-api
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: capa-controller-manager
  name: capa-controller-manager
spec:
  podSelector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-aws
      control-plane: capa-controller-manager
  egress:
    # Kubernetes API on reconciled workload clusters (typically via load balancer), AWS API
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
          protocol: TCP
        - port: 6443
          protocol: TCP
    # Allow dns resolution
    - to:
        - podSelector:
            matchLabels:
              k8s-app: coredns
          namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - port: "1053"
          protocol: UDP
        - port: "1053"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
    # Allow dns resolution
    - to:
        - podSelector:
            matchLabels:
              k8s-app: k8s-dns-node-cache
          namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - port: "1053"
          protocol: UDP
        - port: "1053"
          protocol: TCP
        - port: "53"
          protocol: UDP
        - port: "53"
          protocol: TCP
  policyTypes:
    - Egress
