apiVersion: v1
kind: Secret
metadata:
  name: capa-manager-bootstrap-credentials
  namespace: capa-system
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.provider.capi.accessKeyID| quote }}
    aws_secret_access_key: {{ .Values.provider.capi.secretAccessKey| quote }}
    region: {{ .Values.provider.region| quote }}
data: null
