{{- if .Values.featuregates.eks }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-eks-control-plane-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}-eks-control-plane-webhook
subjects:
- kind: ServiceAccount
  name: {{ include "resource.default.name" . }}-eks-control-plane-webhook
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
