{{ if eq (include "resource.app.unique" .) "false" }}
{{ if eq ({{ .Values.featuregates.eks }}) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-eks-control-plane-leader-election
  namespace: {{ include "resource.default.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "resource.default.name" . }}-eks-control-plane-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "resource.default.name" . }}-eks-control-plane
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
{{ end }}
