{{ if eq ({{ .Values.featuregates.eks }}) "true" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.default.name" . }}-eks-control-plane-webhook
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - port: 443
    targetPort: webhook-server
  selector:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
