{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.ekscontrolplane.name" . }}-webhook
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.ekscontrolplane.name" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.ekscontrolplane.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha3-awsmanagedcontrolplane
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ include "resource.app.version" . }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanes
  sideEffects: None
{{ end }}
