{{- if and (eq (include "resource.app.unique" .) "false") (eq .Values.featuregates.eks "true") }}
apiVersion: v1
data:
  credentials: |-
    {{- if .Values.Installation.V1.Secret.CAPI.AWS }}
    [default]
    aws_access_key_id: {{ .Values.Installation.V1.Secret.CAPI.AWS.AccessKeyID| quote }}
    aws_secret_access_key: {{ .Values.Installation.V1.Secret.CAPI.AWS.SecretAccessKey| quote }}
    region: {{ .Values.Installation.V1.Secret.CAPI.AWS.Region| quote }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  {{ include "resource.default.name" . }}-eks-control-plane-credentials
 namespace: {{ include "resource.default.namespace" . }}
type: Opaque
{{ end }}
