{{- if .Values.featuregates.eks }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.ekscontrolplane.name" . }}-webhook
  namespace: {{ include "resource.default.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.eks.controlplane" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "labels.eks.controlplane" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=0.0.0.0:{{ .Values.ports.metrics }}
        - --webhook-port={{ .Values.ports.webhook }}
        command:
        - /manager
        env:
        image: "{{ .Values.registry.domain }}/{{ .Values.eks.controlplane.image.name }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: {{ .Values.ports.webhook }}
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "resource.ekscontrolplane.name" . }}-webhook
{{ end }}
