{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.ekscontrolplane.name" . }}-leader-election
  namespace: {{ include "resource.default.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "resource.ekscontrolplane.name" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "resource.ekscontrolplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
