{{- if and (eq (include "resource.app.unique" .) "false") (eq .Values.featuregates.eks "true") }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-eks-control-plane-metrics
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
{{ end }}
