{{ if eq (include "resource.app.unique" .) "false" }}
{{ if eq ({{ .Values.featuregates.eks }}) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.default.name" . }}-eks-control-plane
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
