{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.ekscontrolplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
