{{- if .Values.featuregates.eks }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.ekscontrolplane.name" . }}-webhook
{{ end }}
