{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.ekscontrolplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.eks.controlplane" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "labels.eks.controlplane" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --metrics-addr=0.0.0.0:{{ .Values.ports.metrics }}
        - --feature-gates=EKSEnableIAM={{ .Values.featuregates.eksenableiam }},EKSEnableIAM={{ .Values.featuregates.eksallowedroles }},MachinePool={{ .Values.featuregates.machinepool }}
        - --v=4
        - --watch-filter={{ .Values.watchfilter }}
        command:
        - /manager
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /home/.aws/credentials
        image: "{{ .Values.registry.domain }}/{{ .Values.eks.controlplane.image.name }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        name: manager
        ports:
        - containerPort: {{ .Values.ports.metrics }}
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /home/.aws
          name: credentials
      metadata:
        annotations:
          iam.amazonaws.com/role: {{ .Values.aws.arn }}:=""
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ include "resource.ekscontrolplane.name" . }}
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: credentials
        secret:
          secretName: {{ include "resource.ekscontrolplane.name" . }}-credentials
{{ end }}
