{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    control-plane: controller-manager
  name: {{ include "resource.default.name" . }}-eks-control-plane
  namespace: {{ include "resource.default.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.eks.controlplane" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      labels:
        {{- include "labels.eks.controlplane" . | nindent 8 }}
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.rbacproxy.image.name }}:{{ .Values.rbacproxy.image.tag }}"
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: http
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --feature-gates=EKSEnableIAM={{ .Values.featuregates.eksenableiam }},EKSEnableIAM={{ .Values.featuregates.eksallowedroles }},MachinePool={{ .Values.featuregates.machinepool }}
        - --v=4
        - --watch-filter={{ include "resource.app.version" . }}
        command:
        - /manager
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /home/.aws/credentials
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.eks.controlplane.image.name }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        name: manager
        volumeMounts:
        - mountPath: /home/.aws
          name: credentials
      metadata:
        annotations:
          iam.amazonaws.com/role: {{ .Values.aws.arn }}:=""
      securityContext:
        fsGroup: 1000
      serviceAccountname: {{ include "resource.default.name" . }}-eks-control-plane
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: credentials
        secret:
          secretName: {{ include "resource.default.name" . }}-eks-control-plane-credentials
{{ end }}
