{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    component: eks-control-plane
  name: {{ include "resource.ekscontrolplane.name" . }}-metrics
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.ports.metrics }}
    targetPort: http
  selector:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
    component: eks-control-plane
{{ end }}
