{{- if .Values.featuregates.eks }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: controller-manager
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.ekscontrolplane.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
