{{- if .Values.featuregates.eks }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: capa-controller-manager
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-eks-control-plane-webhook
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
