{{- if and (eq (include "resource.app.unique" .) "false") (.Values.featuregates.eks) }}
apiVersion: v1
stringData:
  credentials: |-
    {{- if .Values.provider.capi }}
    [default]
    aws_access_key_id: {{ .Values.provider.capi.accessKeyID| quote }}
    aws_secret_access_key: {{ .Values.provider.capi.secretAccessKey| quote }}
    region: {{ .Values.provider.region| quote }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.ekscontrolplane.name" . }}-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
{{ end }}
