{{- if and (eq (include "resource.app.unique" .) "false") (eq .Values.featuregates.eks "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.eks.controlplane" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-eks-control-plane-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}-eks-control-plane-manager
- kind: ServiceAccount
  name: {{ include "resource.default.name" . }}-eks-control-plane
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
