---
Installation:
  V1:
    Registry:
      Domain: quay.io
    Secret:
      CAPI:
        AWS:
          AccessKeyID: defaultID
          SecretAccessKey: defaultKey
          Region: defaultRegion
    Guest:
      SSH:
        SSOPublicKey: 'ssh-rsa AAASbn3n fake@giantswarm'
