---
Installation:
  V1:
    Registry:
      Domain: quay.io
    Secret:
      CAPI:
        AWS:
          AccessKeyID: defaultID
          SecretAccessKey: defaultKey
          Region: defaultRegion
