---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.webhook.namespace" . }}
spec:
  dnsNames:
  - {{ include "resource.default.name" . }}-webhook.{{ include "resource.webhook.namespace" . }}.svc
  - {{ include "resource.default.name" . }}-webhook.{{ include "resource.webhook.namespace" . }}.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-giantswarm
  secretName: {{ include "resource.default.name" . }}-cert
