---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.webhook.namespace" . }}
spec:
  dnsNames:
  - {{ include "resource.default.name" . }}.{{ include "resource.webhook.namespace" . }}.svc
  - {{ include "resource.default.name" . }}.{{ include "resource.webhook.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "resource.default.name" . }}
  secretName: {{ include "resource.default.name" . }}-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.webhook.namespace" . }}
spec:
  selfSigned: {}
