{{ if eq (include "resource.app.unique" .) "false" }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awscluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awscluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsclustercontrolleridentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclustercontrolleridentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustercontrolleridentities
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsclusterroleidentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclusterroleidentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterroleidentities
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachinetemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachinetemplate.infrastructure.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsfargateprofile
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsfargateprofile.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - fargateprofiles
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1alpha3-awsmanagedmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedmachinepools
  sideEffects: None
{{ end }}
