apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/capa-serving-cert'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-aws
    helm.sh/chart: '{{ .Chart.Name }}'
  name: zzz-capa-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awscluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awscluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsclustercontrolleridentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclustercontrolleridentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustercontrolleridentities
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsclusterroleidentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclusterroleidentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterroleidentities
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsclusterstaticidentity
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclusterstaticidentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterstaticidentities
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsclustertemplate.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsmachine
  failurePolicy: Fail
  name: mutation.awsmachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachines
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsfargateprofile
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsfargateprofile.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsfargateprofiles
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-infrastructure-cluster-x-k8s-io-v1beta1-awsmanagedmachinepool
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedmachinepools
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-bootstrap-cluster-x-k8s-io-v1beta1-eksconfig
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.eksconfigs.bootstrap.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfig
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-bootstrap-cluster-x-k8s-io-v1beta1-eksconfigtemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.eksconfigtemplates.bootstrap.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfigtemplate
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capa-webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-controlplane-cluster-x-k8s-io-v1beta1-awsmanagedcontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: capi
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanes
  sideEffects: None
