{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: cluster-api
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team"
      }}'
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: capa-controller-manager
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capa-default-deny
  namespace: '{{ .Release.Namespace }}'
spec:
  egress:
  - {}
  endpointSelector:
    matchLabels:
      cluster.x-k8s.io/provider: infrastructure-aws
      control-plane: capa-controller-manager
  ingress:
  - {}
{{- end }}
