apiVersion: v1
stringData:
  credentials: |- 
    {{- if .Values.Installation.V1.Secret.Credentiald.CAPI.AWS }}
    [default]
    aws_access_key_id: {{ .Values.Installation.V1.Secret.CAPI.AWS.AccessKeyID | b64enc | quote }}
    aws_secret_access_key: {{ .Values.Installation.V1.Secret.CAPI.AWS.SecretAccessKey | b64enc | quote }}
    region: {{ .Values.Installation.V1.Secret.CAPI.AWS.Region | b64enc | quote }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
