apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
