apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{ .Values.aws.role.arn }}/#arn/eks.amazonaws.com/role-arn: arn
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: controller-manager
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
