apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{ .Values.aws.role.arn }}/#arn/eks.amazonaws.com/role-arn: arn
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: controller-manager
  name: capa-controller-manager
  namespace: capa-system
