apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.namespace" . }}
