{{ if eq (include "resource.app.unique" .) "false" }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    control-plane: capa-controller-manager
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-metrics
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - name: https
    port: {{ .Values.ports.proxy }}
    targetPort: https
  selector:
    {{- include "labels.selector" . | nindent 4 }}
{{ end }}
