apiVersion: v1
data:
  credentials: 
    aws_access_key_id: {{ .Values.aws.accessKeyID }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey }}
    region: {{ .Values.aws.region }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
