apiVersion: v1
stringData:
  credentials: |-
    [default]
    aws_access_key_id: {{ .Values.Installation.V1.Secret.CAPA.AWS.AccessKeyID | quote }}
    aws_secret_access_key: {{ .Values.Installation.V1.Secret.CAPA.AWS.SecretAccessKey | quote }}
    region: {{ .Values.Installation.V1.Secret.CAPA.AWS.Region | quote }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
