{{ if eq (include "resource.app.unique" .) "false" }}
apiVersion: v1
stringData:
  credentials: |-
    {{- if .Values.secret.provider.capi }}
    [default]
    aws_access_key_id: {{ .Values.secret.provider.capi.accessKeyID| quote }}
    aws_secret_access_key: {{ .Values.secret.provider.capi.secretAccessKey| quote }}
    region: {{ .Values.provider.region| quote }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-aws-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
{{ end }}
