apiVersion: v1
stringData:
  credentials.yaml: |- 
    aws_access_key_id: {{ .Values.aws.aws_access_key_id | b64enc | quote }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey | b64enc | quote }}
    region: {{ .Values.aws.region | b64enc | quote }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
