apiVersion: v1
data:
  credentials: 
    aws_access_key_id: {{ .Values.aws.accessKeyID }}
    aws_secret_access_key: {{ .Values.aws.secretAccessKey }}
    region: {{ .Values.Installation.V1.Provider.AWS.Region }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-manager-bootstrap-credentials
  namespace: capa-system
type: Opaque
