apiVersion: v1
kind: Service
metadata:
  labels:
    component: capa-controller-manager
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
  namespace: {{ include "resource.default.namespace" . }}
spec:
  ports:
  - port: {{ .Values.ports.webhook }}
    targetPort: webhook-server
  selector:
    component: capa-controller-manager
    {{- include "labels.selector.infrastructure" . | nindent 4 }}
