apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    application.giantswarm.io/team: '{{ index .Chart.Annotations "application.giantswarm.io/team"
      | quote }}'
    cluster.x-k8s.io/provider: infrastructure-aws
    control-plane: controller-manager
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capa-controller-manager
  namespace: '{{ .Release.Namespace }}'
