apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ include "resource.default.namespace" . }}/{{ include "resource.default.name" . }}
  labels:
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awscluster
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awscluster.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusters
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsclustercontrolleridentity
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclustercontrolleridentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustercontrolleridentities
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsclusterroleidentity
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclusterroleidentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterroleidentities
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsclusterstaticidentity
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclusterstaticidentity.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclusterstaticidentities
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsclustertemplate
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsclustertemplate.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsclustertemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsmachine
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachine.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachines
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsmachinetemplate
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachinetemplate.infrastructure.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinetemplates
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsfargateprofile
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsfargateprofile.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fargateprofiles
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsmachinepool
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-awsmanagedmachinepool
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmanagedmachinepool.infrastructure.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedmachinepools
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-bootstrap-cluster-x-k8s-io-v1beta1-eksconfig
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.eksconfigs.bootstrap.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfig
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-bootstrap-cluster-x-k8s-io-v1beta1-eksconfigtemplate
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.eksconfigtemplates.bootstrap.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - bootstrap.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eksconfigtemplate
  sideEffects: None
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "resource.default.name" . }}-webhook
      namespace: {{ include "resource.default.namespace" . }}
      path: /validate-controlplane-cluster-x-k8s-io-v1beta1-awsmanagedcontrolplane
      port: {{ .Values.ports.webhook }}
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validation.awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  objectSelector:
    matchLabels:
      cluster.x-k8s.io/watch-filter: {{ .Values.watchfilter }}
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsmanagedcontrolplanes
  sideEffects: None
