{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "capa.crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "capa.CRDInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capa.crdInstall" . | quote }}
    {{- include "capa.selectorLabels" . | nindent 4 }}
    role: {{ include "capa.CRDInstallSelector" . | quote }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "capa.crdInstall" . | quote }}
      {{- include "capa.selectorLabels" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
